#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install wget with IRI support
brew install wget --enable-iri

# Growlnotify for doing Growl in shell scripts
brew install growlnotify

# Useful development tools
brew install ack rename tree hub git-extras findutils s3cmd gnu-tar go
brew install rbenv ruby-build
brew install go hg subversion

# Remove outdated versions from the cellar

